# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
    pull_request:
        branches:
            - dev
            - master

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8 # Specify the pnpm version you want to use

            - name: Set node version to 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - run: pnpm install

            - name: Run unit tests
              run: pnpm run test:unit
